#!/usr/bin/env python3
"""
Generate the client-side search index for the guide.

Reads the built pages in build/output/app-router-guide_html/sections/, splits each into sections at
its h1/h2/h3 headings, and writes build/output/app-router-guide_html/assets/search-index.js: a plain
script that assigns window.ARG_SEARCH_INDEX. A <script src> tag works over
file:// where fetch()ing JSON would not, which keeps the guide fully static
and distributable. nav.js consumes the index for the sidebar search box.

Runs as part of `npm run build`, AFTER astro build (it reads build output).
"""
import html as htmllib
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read(p):
    with open(os.path.join(ROOT, p)) as f:
        return f.read()


# ---------- TOC from src/data/toc.js (same tolerant parse as build_artifact.py) ----------
nav = read("src/data/toc.js")
group_re = re.compile(
    r"\{\s*part:\s*(null|['\"][^'\"]*['\"])\s*,(?:\s*cls:\s*['\"][^'\"]*['\"]\s*,)?\s*items:\s*\[(.*?)\]\s*,?\s*\}", re.S
)
item_re = re.compile(
    r"\{\s*n:\s*(['\"])(\d+)\1\s*,\s*title:\s*(['\"])(.*?)\3\s*,\s*file:\s*(['\"])(.*?)\5[^{}]*\}",
    re.S,
)
flat = []
for gm in group_re.finditer(nav):
    for im in item_re.finditer(gm.group(2)):
        flat.append(dict(n=int(im.group(2)), title=im.group(4), file=im.group(6)))
assert len(flat) >= 18, "TOC parse failed"

HEADING = re.compile(r'<h([123])(?:\s+id="([^"]*)")?[^>]*>(.*?)</h\1>', re.S)


def clean(fragment):
    """Tag-stripped, whitespace-collapsed, entity-decoded text."""
    fragment = re.sub(r"<svg\b.*?</svg>", " ", fragment, flags=re.S)
    fragment = re.sub(r"<style\b.*?</style>", " ", fragment, flags=re.S)
    fragment = re.sub(r"<script\b.*?</script>", " ", fragment, flags=re.S)
    fragment = re.sub(r"<[^>]+>", " ", fragment)
    fragment = htmllib.unescape(fragment)
    return re.sub(r"\s+", " ", fragment).strip()


entries = []
for item in flat:
    page = read(f'build/output/app-router-guide_html/sections/{item["file"]}')
    m = re.search(r'<div class="content-inner(?: cover)?">(.*)</div>\s*</main>', page, re.S)
    assert m, item["file"]
    content = m.group(1)

    # Split the page into [pre-heading chunk][heading][chunk][heading][chunk]...
    marks = list(HEADING.finditer(content))
    sections = []
    for i, hm in enumerate(marks):
        body_start = hm.end()
        body_end = marks[i + 1].start() if i + 1 < len(marks) else len(content)
        sections.append(
            dict(
                anchor=hm.group(2) or "",
                heading=clean(hm.group(3)),
                body=clean(content[body_start:body_end]),
            )
        )
    for s in sections:
        if not s["heading"] and not s["body"]:
            continue
        entries.append(
            dict(
                f=item["file"],
                a=s["anchor"],
                n=item["n"],
                c=item["title"],
                h=s["heading"],
                t=s["body"][:2400],
            )
        )

payload = json.dumps(dict(v=1, entries=entries), ensure_ascii=False, separators=(",", ":"))
payload = payload.replace("</", "<\\/")  # never terminate the script tag early
body = (
    "/* generated by scripts/build_search_index.py - do not edit */\n"
    f"window.ARG_SEARCH_INDEX = {payload};\n"
)
# build/output/app-router-guide_html/assets: the distributable. public/assets: so the astro DEV
# server serves it too (public/ is what dev serves; the copy is refreshed each build).
outs = ["build/output/app-router-guide_html/assets/search-index.js", "public/assets/search-index.js"]
for rel in outs:
    with open(os.path.join(ROOT, rel), "w") as f:
        f.write(body)
size = len(body) // 1024
print(f"search index: {len(entries)} sections, {size} KB -> {', '.join(outs)}")
